trigger: none
pr: none

parameters:
  - name: env
    displayName: Environment
    type: string
    default: nonprod
    values: [nonprod, prod]

  - name: destroy
    displayName: Destroy
    type: boolean
    default: false

variables:
  TF_DIR: terraform
  TF_VAR_FILE: 'terraform/${{ parameters.env }}.tfvars'
  TF_STATE_BUCKET: cloud-native-devops-platform-terraform-bucket
  TF_STATE_KEY: 'state/${{ parameters.env }}.tfstate'
  AWS_SERVICE_CONNECTION: hamouda

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - task: TerraformInstaller@1
    displayName: Install Terraform
    inputs:
      terraformVersion: latest

  - task: AWSShellScript@1
    displayName: Terraform init
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: us-east-1
      scriptType: inline
      inlineScript: |
        set -euo pipefail
        cd "$(TF_DIR)"
        terraform init \
          -backend-config="bucket=$(TF_STATE_BUCKET)" \
          -backend-config="key=$(TF_STATE_KEY)" \
          -backend-config="region=us-east-1" \
          -backend-config="encrypt=true"

  - task: AWSShellScript@1
    displayName: Terraform plan
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: us-east-1
      scriptType: inline
      inlineScript: |
        set -euo pipefail
        cd "$(TF_DIR)"
        if [ "${{ parameters.destroy }}" = "True" ]; then
          terraform plan -destroy -out=tfplan -var-file="../$(TF_VAR_FILE)"
        else
          terraform plan -out=tfplan -var-file="../$(TF_VAR_FILE)"
        fi

  - task: AWSShellScript@1
    displayName: Terraform apply
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: us-east-1
      scriptType: inline
      inlineScript: |
        set -euo pipefail
        cd "$(TF_DIR)"
        terraform apply -auto-approve tfplan
