trigger: none
pr: none

parameters:
- name: env
  type: string
  default: nonprod
  values: [nonprod, prod]

variables:
  AWS_REGION: us-east-1
  AWS_SERVICE_CONNECTION: aws-cred

jobs:
- job: apply_argocd
  pool: { name: aws-self-hosted }
  steps:
  - checkout: self

  - task: AWSShellScript@1
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        set -euo pipefail

        aws eks update-kubeconfig --region $(AWS_REGION) --name "${{ parameters.env }}-eks"

        kubectl wait --for=condition=Established crd/applications.argoproj.io crd/appprojects.argoproj.io --timeout=2m
        kubectl apply -f argocd/projects/voting-app.yaml
        kubectl apply -f "argocd/apps/voting-app-${{ parameters.env }}.yaml"
        
