trigger: none
pr: none

parameters:
- name: env
  type: string
  default: nonprod
  values: [nonprod, prod]

variables:
  AWS_REGION: us-east-1
  AWS_SERVICE_CONNECTION: aws-cred
  NEXUS_SERVER: nexus.3bdo7amouda.tech

jobs:
- job: seed_secret
  pool: { name: aws-self-hosted }
  steps:
  - checkout: self

  - task: AWSShellScript@1
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        set -euo pipefail q

        aws eks update-kubeconfig --region $(AWS_REGION) --name "${{ parameters.env }}-eks"

        : "${NEXUS_USERNAME:?}" "${NEXUS_PASSWORD:?}"
        : "${MONGODB_ATLAS_HOST:?}" "${MONGODB_ATLAS_USER:?}" "${MONGODB_ATLAS_PASSWORD:?}"

        PY="$(command -v python3 || command -v python)"
        HOST="${MONGODB_ATLAS_HOST#mongodb+srv://}"; HOST="${HOST#mongodb://}"; HOST="${HOST%/}"; HOST="${HOST%%/*}"

        U="$("$PY" -c 'import os,urllib.parse; print(urllib.parse.quote(os.environ["MONGODB_ATLAS_USER"], safe=""))')"
        P="$("$PY" -c 'import os,urllib.parse; print(urllib.parse.quote(os.environ["MONGODB_ATLAS_PASSWORD"], safe=""))')"

        kubectl create ns voting-app --dry-run=client -o yaml | kubectl apply -f -
        kubectl -n voting-app create secret docker-registry nexus-pull \
          --docker-server="$(NEXUS_SERVER)" \
          --docker-username="$(NEXUS_USERNAME)" \
          --docker-password="$(NEXUS_PASSWORD)" \
          --docker-email="none@example.com" \
          --dry-run=client -o yaml | kubectl apply -f -
        kubectl -n voting-app create secret generic mongodb-atlas-credentials \
          --from-literal=connection-string="mongodb+srv://${U}:${P}@${HOST}/?retryWrites=true&w=majority" \
          --dry-run=client -o yaml | kubectl apply -f -
    env:
      NEXUS_SERVER: $(NEXUS_SERVER)
      NEXUS_USERNAME: $(NEXUS_USERNAME)
      NEXUS_PASSWORD: $(NEXUS_PASSWORD)
      MONGODB_ATLAS_HOST: $(MONGODB_ATLAS_HOST)
      MONGODB_ATLAS_USER: $(MONGODB_ATLAS_USER)
      MONGODB_ATLAS_PASSWORD: $(MONGODB_ATLAS_PASSWORD)

- job: apply_argocd
  dependsOn: seed_secret
  pool: { name: aws-self-hosted }
  steps:
  - checkout: self

  - task: AWSShellScript@1
    inputs:
      awsCredentials: $(AWS_SERVICE_CONNECTION)
      regionName: $(AWS_REGION)
      scriptType: inline
      inlineScript: |
        set -euo pipefail

        aws eks update-kubeconfig --region $(AWS_REGION) --name "${{ parameters.env }}-eks"

        kubectl wait --for=condition=Established crd/applications.argoproj.io crd/appprojects.argoproj.io --timeout=2m
        kubectl apply -f argocd/projects/voting-app.yaml
        kubectl apply -f "argocd/apps/voting-app-${{ parameters.env }}.yaml"
        
