replicaCount:
  vote: 2
  worker: 0
  result: 2

worker:
  enabled: false

image:
  vote:
    repository: nexus.3bdo7amouda.tech/voting-app/vote
    tag: "latest"
    pullPolicy: Always
  worker:
    repository: nexus.3bdo7amouda.tech/voting-app/worker
    tag: "latest"
    pullPolicy: Always
  result:
    repository: nexus.3bdo7amouda.tech/voting-app/result
    tag: "latest"
    pullPolicy: Always

imagePullSecrets:
  - name: nexus-pull

mongodb:
  secretName: mongodb-atlas-credentials
  secretKey: connection-string
  databaseName: voting

service:
  vote:
    type: ClusterIP
    port: 80
    targetPort: 80
  result:
    type: ClusterIP
    port: 80
    targetPort: 4000

resources:
  vote:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  worker:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "400m"
  result:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

ingress:
  enabled: false
  className: alb
  annotations: {}
  hosts:
    - paths:
        - path: /api/vote
          pathType: Prefix
          service: vote
          port: 80
        - path: /api/result
          pathType: Prefix
          service: result
          port: 80
