ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/group.name: platform
    alb.ingress.kubernetes.io/load-balancer-name: nonprod-alb
    alb.ingress.kubernetes.io/success-codes: "200-499"
    alb.ingress.kubernetes.io/healthcheck-path: /healthz

image:
  vote:
    repository: nexus.3bdo7amouda.tech/voting-app/vote
  worker:
    repository: nexus.3bdo7amouda.tech/voting-app/worker
  result:
    repository: nexus.3bdo7amouda.tech/voting-app/result

imagePullSecrets:
  - name: nexus-pull
