apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-app.fullname" . }}-vote
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: vote
spec:
  replicas: {{ .Values.replicaCount.vote }}
  selector:
    matchLabels:
      {{- include "voting-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: vote
  template:
    metadata:
      labels:
        {{- include "voting-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: vote
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: vote
        image: "{{ .Values.image.vote.repository }}:{{ .Values.image.vote.tag }}"
        imagePullPolicy: {{ .Values.image.vote.pullPolicy }}
        env:
        - name: BASE_PATH
          value: /api/vote
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongodb.secretName }}
              key: {{ .Values.mongodb.secretKey }}
        - name: DATABASE_NAME
          value: {{ .Values.mongodb.databaseName | quote }}
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          {{- toYaml .Values.resources.vote | nindent 10 }}
