apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-pull
  namespace: voting-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nexus-pull
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: "nexus/registry"
        property: "dockerconfigjson"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-atlas-credentials
  namespace: voting-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mongodb-atlas-credentials
    creationPolicy: Owner
  data:
    - secretKey: connection-string
      remoteRef:
        key: "mongodb/atlas"
        property: "connection-string"
