apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: argocd-nlb-tgb
  namespace: argocd
spec:
  targetGroupARN: TARGET_GROUP_ARN_PLACEHOLDER
  targetType: ip
  serviceRef:
    name: argocd-server
    port: 80
