apiVersion: v1
kind: Namespace
metadata:
  name: platform-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-router
  namespace: platform-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: platform-router
  template:
    metadata:
      labels:
        app: platform-router
    spec:
      tolerations:
      - key: platform
        operator: Equal
        value: "true"
        effect: NoSchedule
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: platform-router
  namespace: platform-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: platform-router
