apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarqube-token
  namespace: sonarqube
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-sonarqube
  target:
    name: sonarqube-token
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: token
      remoteRef:
        key: sonarqube/ci
        property: token
    - secretKey: host
      remoteRef:
        key: sonarqube/ci
        property: host
