apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-sonarqube
spec:
  provider:
    vault:
      server: http://34.195.126.205:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-sonarqube
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
