apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-token
  namespace: sonarqube
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: sonarqube-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: sonarqube/token
        property: token
    - secretKey: host
      remoteRef:
        key: sonarqube/token
        property: host
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-token
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: sonarqube-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: sonarqube/token
        property: token
    - secretKey: host
      remoteRef:
        key: sonarqube/token
        property: host
