apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: platform-nlb-tgb
  namespace: platform-backend
spec:
  targetGroupARN: TARGET_GROUP_ARN_PLACEHOLDER
  targetType: ip
  serviceRef:
    name: platform-router
    port: 80
