apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: ingress-nlb-tgb
  namespace: ingress-nginx
spec:
  targetGroupARN: TARGET_GROUP_ARN_PLACEHOLDER
  targetType: ip
  serviceRef:
    name: ingress-nginx-controller
    port: 80
